name: project_2024
description: "A new Flutter project."
publish_to: "none"

version: 1.2.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_date_timeline: ^1.1.3
  timelines: ^0.1.0
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  confetti: ^0.8.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  calendar_date_picker2: ^1.1.7
  animated_toggle_switch: ^0.8.3
  adaptive_theme: ^3.6.0
  salomon_bottom_bar: ^3.3.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  adhan: ^2.0.0+1
  flutter_adaptive_scaffold: ^0.3.1
  flutter_local_notifications: ^17.2.3
  android_alarm_manager_plus: ^4.0.4
  awesome_notifications: ^0.9.3+1
  transformable_list_view: ^0.6.0
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
